-- Supabase SQL Editor मध्ये हा code run करा.
-- Table + public demo policies create होतील.

create table if not exists appointments (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  doctor text,
  department text,
  date text,
  time text,
  message text,
  payment_status text default 'Unpaid',
  appointment_status text default 'Pending',
  admin_note text default '',
  created_at timestamp with time zone default now()
);

alter table appointments enable row level security;

drop policy if exists "Allow public insert appointments" on appointments;
drop policy if exists "Allow public read appointments" on appointments;
drop policy if exists "Allow public update appointments" on appointments;
drop policy if exists "Allow public delete appointments" on appointments;

create policy "Allow public insert appointments"
on appointments for insert
to anon
with check (true);

create policy "Allow public read appointments"
on appointments for select
to anon
using (true);

create policy "Allow public update appointments"
on appointments for update
to anon
using (true)
with check (true);

create policy "Allow public delete appointments"
on appointments for delete
to anon
using (true);
